### ISSUE TITLE
query me failed with 422 internal server error

### ISSUE THREAD

**Issue by ling7334** [ling7334/hoppscotch-backend-go#4]
### log
```
2024-02-16T04:01:54Z 2024-02-16T04:01:54Z DBG 2024-02-16T04:01:54Z 2024-02-16T04:01:54Z DBG 2024-02-16T04:01:54Z 2024-02-16T04:01:54Z DBG 2024-02-16T04:01:54Z 2024-02-16T04:01:54Z DBG uid: ***
2024-02-16T04:01:54Z 2024-02-16T04:01:54Z INF 2024-02-16T04:01:54Z 2024-02-16T04:01:54Z INF 2024-02-16T04:01:54Z 2024-02-16T04:01:54Z INF 2024-02-16T04:01:54Z 2024-02-16T04:01:54Z INF IsLogIn | 2024-02-16T04:01:54Z 2024-02-16T04:01:54Z INF 2024-02-16T04:01:54Z 2024-02-16T04:01:54Z INF 2024-02-16T04:01:54Z 2024-02-16T04:01:54Z INF 2024-02-16T04:01:54Z 2024-02-16T04:01:54Z INF IsLogIn | obj=null
json: error calling MarshalJSON for type json.RawMessage: invalid character '-' after object key:value pair
goroutine 49 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x13
github.com/99designs/gqlgen/graphql.DefaultRecover({0xc0003031c0?, 0xc0003031c0?}, {0xcf5f40?, 0xc0003a8ab0?})
	/go/pkg/mod/github.com/99designs/gqlgen@v0.17.42/graphql/recovery.go:17 +0x6b
github.com/99designs/gqlgen/graphql/executor.(*Executor).PresentRecoveredError(0xc00030a280, {0xeff908, 0xc00035cb40}, {0xcf5f40?, 0xc0003a8ab0?})
	/go/pkg/mod/github.com/99designs/gqlgen@v0.17.42/graphql/executor/executor.go:157 +0x43
github.com/99designs/gqlgen/graphql/handler.(*Server).ServeHTTP.func1()
	/go/pkg/mod/github.com/99designs/gqlgen@v0.17.42/graphql/handler/server.go:105 +0x99
panic({0xcf5f40?, 0xc0003a8ab0?})
	/usr/local/go/src/runtime/panic.go:914 +0x21f
github.com/99designs/gqlgen/graphql/handler/transport.writeJson({0xef7940, 0xc000346540}, 0xc00035cb40?)
	/go/pkg/mod/github.com/99designs/gqlgen@v0.17.42/graphql/handler/transport/util.go:16 +0x5c
github.com/99designs/gqlgen/graphql/handler/transport.POST.Do({0xeff908?}, {0xefdf48?, 0xc000346540}, 0xc000315600, {0xefe098, 0xc00030a280})
	/go/pkg/mod/github.com/99designs/gqlgen@v0.17.42/graphql/handler/transport/http_post.go:91 +0x587
github.com/99designs/gqlgen/graphql/handler.(*Server).ServeHTTP(0xc0000760c0, {0xefdf48?, 0xc000346540}, 0xc000315600)
	/go/pkg/mod/github.com/99designs/gqlgen@v0.17.42/graphql/handler/server.go:122 +0x278
main.main.OperatorMiddleware.func5.1()
	/app/pkg/middleware/db.go:26 +0x2b
main.main.OperatorMiddleware.func5({0xefdf48?, 0xc000346540?}, 0xc000315500)
	/app/pkg/middleware/db.go:38 +0x21f
net/http.HandlerFunc.ServeHTTP(0xca8a20?, {0xefdf48?, 0xc000346540?}, 0xef5360?)
	/usr/local/go/src/net/http/server.go:2136 +0x29
main.main.JwtMiddleware.func6.1()
	/app/pkg/middleware/jwt.go:71 +0x2b
main.main.JwtMiddleware.func6({0xefdf48?, 0xc000346540}, 0xc000315400)
	/app/pkg/middleware/jwt.go:166 +0x8c4
net/http.HandlerFunc.ServeHTTP(0xc0000a0ae8?, {0xefdf48?, 0xc000346540?}, 0xc000012d20?)
	/usr/local/go/src/net/http/server.go:2136 +0x29
main.main.LogMiddleware.func7.1()
	/app/pkg/middleware/log.go:15 +0x54
main.main.LogMiddleware.func7({0xefdf48?, 0xc000346540}, 0xc000315300)
	/app/pkg/middleware/log.go:18 +0xdc
net/http.HandlerFunc.ServeHTTP(0x10?, {0xefdf48?, 0xc000346540?}, 0xc000312c2c?)
	/usr/local/go/src/net/http/server.go:2136 +0x29
net/http.(*ServeMux).ServeHTTP(0x410985?, {0xefdf48, 0xc000346540}, 0xc000315300)
	/usr/local/go/src/net/http/server.go:2514 +0x142
net/http.serverHandler.ServeHTTP({0xefb500?}, {0xefdf48?, 0xc000346540?}, 0x6?)
	/usr/local/go/src/net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc000327710, {0xeff908, 0xc000308720})
	/usr/local/go/src/net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 1
	/usr/local/go/src/net/http/server.go:3086 +0x5cb
2024-02-16T04:01:54Z 2024-02-16T04:01:54Z INF 2024-02-16T04:01:54Z 2024-02-16T04:01:54Z INF 2024-02-16T04:01:54Z 2024-02-16T04:01:54Z INF 2024-02-16T04:01:54Z 2024-02-16T04:01:54Z INF 127.0.0.1:56374 [POST] /graphql in 7.199608ms 
172.20.0.3 - - [16/Feb/2024:04:01:54 +0000] "POST /graphql HTTP/1.1" 422 60 "https://hoppscotch.**.**/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"

```

**Comment by ling7334** [comment]
fix in 5c250c9f629eef61f1dd0d5dede16a662f8e015e
